return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 6,
  height = 6,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 7,
  nextobjectid = 25,
  properties = {},
  tilesets = {
    {
      name = "1",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "../assets/Franky/forwardAir/1.png",
      imagewidth = 96,
      imageheight = 96,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "2",
      firstgid = 37,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "../assets/Franky/forwardAir/2.png",
      imagewidth = 96,
      imageheight = 96,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "3",
      firstgid = 73,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "../assets/Franky/forwardAir/3.png",
      imagewidth = 96,
      imageheight = 96,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "4",
      firstgid = 109,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "../assets/Franky/forwardAir/4.png",
      imagewidth = 96,
      imageheight = 96,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "tiles",
      firstgid = 145,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 14,
      image = "../assets/tiles.png",
      imagewidth = 224,
      imageheight = 64,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 56,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 6,
      height = 6,
      id = 6,
      name = "ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,
        191, 191, 191, 191, 191, 191
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 6,
      height = 6,
      id = 1,
      name = "frame1",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 2, 3, 4, 5, 6,
        7, 8, 9, 10, 11, 12,
        13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24,
        25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 6,
      height = 6,
      id = 3,
      name = "frame2",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        37, 38, 39, 40, 41, 42,
        43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60,
        61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 6,
      height = 6,
      id = 4,
      name = "frame3",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        73, 74, 75, 76, 77, 78,
        79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96,
        97, 98, 99, 100, 101, 102,
        103, 104, 105, 106, 107, 108
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 6,
      height = 6,
      id = 5,
      name = "frame4",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120,
        121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "hitboxes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 14,
          name = "Hitbox",
          type = "forwardAir3",
          shape = "ellipse",
          x = 53,
          y = 26.5,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "Hitbox",
          type = "forwardAir3",
          shape = "ellipse",
          x = 56,
          y = 31,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "Hitbox",
          type = "forwardAir3",
          shape = "ellipse",
          x = 57.375,
          y = 37.375,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "Hitbox",
          type = "forwardAir3",
          shape = "ellipse",
          x = 56.625,
          y = 44.625,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "Hitbox",
          type = "forwardAir3",
          shape = "ellipse",
          x = 53,
          y = 51,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "Hitbox",
          type = "forwardAir3",
          shape = "ellipse",
          x = 48.25,
          y = 56.5,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "Hitbox",
          type = "forwardAir3",
          shape = "ellipse",
          x = 41.625,
          y = 60.375,
          width = 20,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
